# Generated by Django 5.2 on 2025-04-14 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plaidapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plaidaccount',
            name='created_at',
        ),
        migrations.AddField(
            model_name='plaidaccount',
            name='institution_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='plaidaccount',
            name='access_token',
            field=models.TextField(),
        ),
    ]
