# Generated by Django 5.2 on 2025-04-14 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plaidapp', '0002_remove_plaidaccount_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plaidaccount',
            name='institution_name',
        ),
        migrations.AddField(
            model_name='plaidaccount',
            name='institution_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
